
spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3307/serverManage
    username: root
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernte:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
      show-sql: true